version: 2
multi-ecosystem-groups:
  dependencies:
    schedule:
      interval: "cron"
      cronjob: "0 9 * * mon%2" # Every other Monday at 09:00 UTC.
    open-pull-requests-limit: 1
    commit-message:
      prefix: "chore(deps)"
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    allow:
      - dependency-type: "all"
    patterns: ["*"]
    multi-ecosystem-group: "dependencies"
  - package-ecosystem: "docker"
    directory: "/"
    patterns: ["*"]
    multi-ecosystem-group: "dependencies"
  - package-ecosystem: "docker-compose"
    directory: "/"
    patterns: ["*"]
    multi-ecosystem-group: "dependencies"
  - package-ecosystem: "github-actions"
    directory: "/"
    patterns: ["*"]
    multi-ecosystem-group: "dependencies"
